import React,{useEffect,useRef,useState} from 'react';
import {RefreshCw,Search,ChevronRight,SlidersHorizontal,X} from 'lucide-react';
import {request} from './api';
import {useViewState} from './view-state';
import {hubChannels,hubView,commonValue,isHubResponse,hubConfiguredDisabled,type HubRow} from './model-hub';
import {ModelMetadata} from './secondary-pages';
type T=(key:string)=>string;
type Props={connected:boolean,busy:boolean,config:HubRow|null,t:T,date:(x:any)=>string,fmt:(x:any)=>string,onError:(e:unknown)=>void,onToggle:(m:HubRow,after:()=>Promise<void>)=>void,refreshRef:React.MutableRefObject<(()=>Promise<void>)|null>};
const tok=(n:any)=>typeof n==='number'&&n>0?(n>=1024?Math.round(n/1024)+'K':String(n)):'—';
function HubDialog({row,t,date,fmt,onClose,config,busy,onToggle,after}:{row:HubRow,t:T,date:(x:any)=>string,fmt:(x:any)=>string,onClose:()=>void,config:HubRow|null,busy:boolean,onToggle:Props['onToggle'],after:()=>Promise<void>}){
 const ref=useRef<HTMLDialogElement>(null);useEffect(()=>{ref.current?.showModal();return()=>ref.current?.close()},[]);
 const disabled=hubConfiguredDisabled(row.id,config,!!row.disabled);
 return <dialog ref={ref} className="modal wide hub-dialog" onCancel={e=>{e.preventDefault();onClose()}} aria-label={row.name||row.id}><div className="modal-head"><h2>{row.name||row.id}</h2><button className="button icon ghost" aria-label={t('close')} onClick={onClose}><X size={18}/></button></div><div className="modal-body"><p className="mono">{row.id}</p><p className="muted">{t('hubEvidenceHint')}</p><div className="hub-variants">{row.variants.map((v:HubRow,i:number)=><section className="hub-variant" key={i}><h3>{t('hubChannel_'+v.channel)} <span className={'hub-origin '+v.origin}>{t('hubOrigin_'+v.origin)}</span></h3><p>{v.account_name||v.auth_index||v.config_key||'—'}</p><p className="muted">{v.model.name||v.model.id}</p><ModelMetadata model={v.model} t={t}/><dl className="runtime"><dt>{t('context')}</dt><dd>{v.model.context_length>0?fmt(v.model.context_length)+' tokens':'—'}</dd><dt>{t('output')}</dt><dd>{v.model.max_completion_tokens>0?fmt(v.model.max_completion_tokens)+' tokens':'—'}</dd><dt>{t('series')}</dt><dd>{v.model.family||v.model.vendor||t('otherFamily')}{v.model.family_derived?' · '+t('idDerived'):''}</dd><dt>{t('toolDeclaration')}</dt><dd>{t(v.model.supports_tool_call===true?'declaredYes':v.model.supports_tool_call===false?'declaredNo':'unverified')}</dd><dt>{t('source')}</dt><dd>{v.model.sources?.join(' + ')||v.config_key||'—'}</dd><dt>{t('status')}</dt><dd>{t(v.model.disabled?'upstreamDisabled':v.origin==='dynamic'?'directoryOnly':'hubConfigured')}</dd></dl>{v.model.description&&<p>{v.model.description}</p>}{v.model.tags?.length>0&&<p>{t('tags')}: {v.model.tags.join(' · ')}</p>}{v.model.reasoning_summary&&<p>{t('reasoningSummary')}: {v.model.reasoning_summary}</p>}{v.model.image_input_conflict&&<p className="notice warn">{t('imageConflict')}</p>}{Object.entries(v.model.image_input_sources||{}).map(([key,value])=><p key={key}>{key} · {t(value===true?'imageDeclared':value===false?'textDeclared':'unverified')}</p>)}</section>)}</div><div className="hub-config-control"><div><strong>{t('hubConfigSwitch')}</strong><p className="muted">{t('hubConfigHint')}</p><small>{t(disabled?'disabled':'enabled')}</small></div><button className="button" disabled={busy||!config} onClick={()=>{onClose();onToggle({...row,disabled},after)}}>{t(disabled?'enableModel':'disableModel')}</button></div></div></dialog>
}
export function ModelWorkspace({connected,busy,config,t,date,fmt,onError,onToggle,refreshRef}:Props){
 const [selection,setSelection]=useViewState<Record<string,string>>('hubSources',{}),[query,setQuery]=useViewState('hubQuery',''),[origin,setOrigin]=useViewState('hubOrigin','all'),[channel,setChannel]=useViewState('hubChannel','all'),[sort,setSort]=useViewState('hubSort','sourceOrder'),[sourcesOpen,setSourcesOpen]=useViewState('hubSourcesOpen',false);
 const [data,setData]=useState<HubRow|null>(null),[loading,setLoading]=useState(false),[error,setError]=useState(''),[detail,setDetail]=useState<HubRow|null>(null);const sequence=useRef(0),alive=useRef(true);
 const selectionKey=JSON.stringify(selection);
 async function load(force=false){const seq=++sequence.current;setLoading(true);setError('');setData(null);setDetail(null);try{const params=new URLSearchParams(Object.entries(selection).filter(([ch,id])=>hubChannels.includes(ch)&&!!id));const result=await request(force?'/models/hub/refresh':'/models/hub?'+params.toString(),force?'POST':'GET',force?{sources:selection}:undefined);if(!isHubResponse(result))throw Error('invalidResponse');if(alive.current&&seq===sequence.current)setData(result)}catch(e){if(alive.current&&seq===sequence.current){setError((e as Error).message||'requestFailed');onError(e)}}finally{if(alive.current&&seq===sequence.current)setLoading(false)}}
 useEffect(()=>{alive.current=true;return()=>{alive.current=false;sequence.current++}},[]);
 useEffect(()=>{if(connected)void load();else{setData(null);sequence.current++}},[connected,selectionKey]);
 useEffect(()=>{refreshRef.current=()=>load(true);return()=>{refreshRef.current=null}},[connected,selectionKey]);
 const pool:HubRow[]=data?.models||[];const view=hubView(pool,query,origin,channel,sort);const active=!!query||origin!=='all'||channel!=='all'||sort!=='sourceOrder';const reset=()=>{setQuery('');setOrigin('all');setChannel('all');setSort('sourceOrder')};
 const accountNames=new Map((data?.sources||[]).flatMap((s:HubRow)=>(s.accounts||[]).map((a:HubRow)=>[a.auth_index,a.name])));
 const detailRow=(m:HubRow)=>({...m,variants:m.variants.map((v:HubRow)=>({...v,account_name:accountNames.get(v.auth_index)}))});
 const limits=(m:HubRow,key:string)=>{const c=commonValue(m.variants,key);return c.varied?t('hubVaries'):tok(c.value)};
 const meta=(m:HubRow)=>{const fields=['efforts','default_effort','credits','supports_images','only_reasoning'];if(fields.some(k=>commonValue(m.variants,k).varied))return <span className="hub-varies">{t('hubVaries')}</span>;return <ModelMetadata model={m.variants[0].model} t={t}/>};
 return <section className="model-hub" aria-label={t('hubTitle')}><div className="hub-overview"><div className="hub-counts">{[['hubTotal',pool.length],['hubDynamic',pool.filter(m=>m.variants.some((v:HubRow)=>v.origin==='dynamic')).length],['hubCustom',pool.filter(m=>m.variants.some((v:HubRow)=>v.origin==='custom')).length]].map(([label,n])=><span key={label}><small>{t(String(label))}</small><b>{data?n:'—'}</b></span>)}</div><div className="hub-actions"><button className="button" aria-expanded={sourcesOpen} onClick={()=>setSourcesOpen(x=>!x)}><SlidersHorizontal size={14}/>{t('hubSources')}{data?.status==='partial'&&<i className="filter-dot"/>}</button><button className="button" disabled={!connected||loading||busy} onClick={()=>void load(true)}><RefreshCw size={14} className={loading?'spin':''}/>{t('refetchDirectory')}</button></div></div>
 {sourcesOpen&&<div className="hub-sources"><p>{t('hubSourceHint')}</p><div className="hub-source-grid">{(data?.sources||[]).map((s:HubRow)=><section key={s.channel}><label htmlFor={'hub-source-'+s.channel}>{t('hubChannel_'+s.channel)}</label><select id={'hub-source-'+s.channel} value={selection[s.channel]||''} disabled={loading||busy} onChange={e=>{sequence.current++;setData(null);setDetail(null);setSelection(prev=>({...prev,[s.channel]:e.target.value}))}}><option value="">{t('hubAuto')}</option>{s.accounts.map((a:HubRow)=><option key={a.auth_index} value={a.auth_index} disabled={!a.available}>{a.name}</option>)}{selection[s.channel]&&!s.accounts.some((a:HubRow)=>a.auth_index===selection[s.channel])&&<option value={selection[s.channel]}>{t('hubMissingAccount')}</option>}</select><strong>{s.name||'—'}</strong><small>{t('hubBasis_'+s.basis)} · {t('hubStatus_'+s.status)}{s.cached?' · '+t('cachedDirectory'):''}</small><small>{s.fetched_at?date(s.fetched_at):'—'} · {s.count} {t('hubEntries')}</small>{s.endpoints?.map((e:HubRow)=><small key={e.source}>{e.source}: {e.status==='ok'?e.count:e.error}</small>)}</section>)}</div>{!!data?.account_errors?.length&&<p className="error-text">{t('hubAccountErrors')}: {data.account_errors.length}</p>}</div>}
 {data?.status==='partial'&&<div className="hub-warning" role="status">{t('hubPartial')} <button onClick={()=>setSourcesOpen(true)}>{t('hubSources')}</button></div>}
 <div className="hub-toolbar"><label className="search"><Search size={15}/><input value={query} onChange={e=>setQuery(e.target.value)} aria-label={t('searchModels')} placeholder={t('searchModels')}/></label><select aria-label={t('hubOriginFilter')} value={origin} onChange={e=>setOrigin(e.target.value)}>{['all','dynamic','custom'].map(x=><option key={x} value={x}>{t(x==='all'?'hubAllOrigins':'hubOrigin_'+x)}</option>)}</select><select aria-label={t('hubChannelFilter')} value={channel} onChange={e=>setChannel(e.target.value)}>{['all',...hubChannels].map(x=><option key={x} value={x}>{t(x==='all'?'hubAllChannels':'hubChannel_'+x)}</option>)}</select><select aria-label={t('modelSort')} value={sort} onChange={e=>setSort(e.target.value)}>{['sourceOrder','nameOrder','contextOrder','creditOrder'].map(x=><option key={x} value={x}>{t(x)}</option>)}</select>{active&&<button className="button icon" onClick={reset} aria-label={t('clearFilters')}><X size={15}/></button>}</div>
 {error&&<div className="notice error" role="alert">{t(error)}<button className="button" onClick={()=>void load(true)} disabled={loading}>{t('retry')}</button></div>}
 <section className="table-card hub-table models-table"><div className="table-scroll"><table><thead><tr><th>{t('name')} / ID</th><th>{t('source')}</th><th>{t('hubChannelFilter')}</th><th>{t('context')}</th><th>{t('output')}</th><th>{t('reasoningTier')} / {t('multiplier')}</th><th>{t('actions')}</th></tr></thead><tbody>{view.map((m:HubRow)=><tr key={m.id}><td className="hub-name"><strong>{m.name||m.id}</strong>{m.name!==m.id&&<small className="mono">{m.id}</small>}<span className="hub-mobile-limits">{limits(m,'context_length')} / {limits(m,'max_completion_tokens')}</span></td><td className="hub-origin-cell">{['dynamic','custom'].filter(o=>m.variants.some((v:HubRow)=>v.origin===o)).map(o=><span key={o} className={'hub-origin '+o}>{t('hubOrigin_'+o)}</span>)}</td><td className="hub-channel-cell">{hubChannels.filter(ch=>m.variants.some((v:HubRow)=>v.channel===ch)).map(ch=><span className={'hub-channel '+(m.variants.some((v:HubRow)=>v.channel===ch&&v.origin==='dynamic')?'observed':'configured')} key={ch}>{t('hubChannel_'+ch)}<small>{['dynamic','custom'].filter(o=>m.variants.some((v:HubRow)=>v.channel===ch&&v.origin===o)).map(o=>t('hubShort_'+o)).join(' + ')}{m.variants.filter((v:HubRow)=>v.channel===ch&&v.origin==='dynamic').length>0&&m.variants.filter((v:HubRow)=>v.channel===ch&&v.origin==='dynamic').every((v:HubRow)=>v.model.disabled)?' · '+t('upstreamDisabled'):''}</small></span>)}</td><td className="hub-limit">{limits(m,'context_length')}</td><td className="hub-limit">{limits(m,'max_completion_tokens')}</td><td className="hub-meta">{meta(m)}</td><td className="hub-row-action"><button className="button ghost" onClick={()=>setDetail(detailRow(m))}>{t('hubDetails')}<ChevronRight size={13}/></button></td></tr>)}</tbody></table></div>{!view.length&&<div className="empty"><h3>{t(loading?'loading':!connected?'authRequired':error?'catalogUnavailable':!data?'catalogUnavailable':pool.length?'noMatches':'hubEmpty')}</h3></div>}<div className="table-footer"><span>{t('shown')} {view.length} / {data?pool.length:'—'}</span><span title={t('hubEvidenceHint')}>{t('hubLegend')}</span></div></section>
 {detail&&<HubDialog row={detail} t={t} date={date} fmt={fmt} onClose={()=>setDetail(null)} config={config} busy={busy} onToggle={onToggle} after={()=>load(false)}/>}</section>
}
