import {expiryTimestamp} from './expiry';
import {validTravelRun,businessSupported,settingState,configuredSetting} from './workspace-data';
import {accountMatchesFilter} from './account-status';
import {NextExpiry} from './expiry-clock';
import React from 'react';
type R=Record<string,any>;type T=(key:string)=>string;
export const automationKeys=['checkin_auto','lifecycle_auto','token_keepalive','travel_auto'];
export const pluginDefaults:R={checkin_auto:true,lifecycle_auto:true,token_keepalive:false,travel_auto:false,scheduler_mode:'host'};
export function ExpiryNote({credits,t,fmt,date}:{credits?:R,t:T,fmt:(n:any)=>string,date:(s:any)=>string}){
 const e=credits?.expiry;return <div className="expiry-note"><NextExpiry credits={credits}/><strong>{t('expiring7')}: {e?.known?fmt(e.within_7_days):'—'}</strong>{(!e?.known||e?.unknown_remain>0)&&<span>{t('expiryUnknown')}{e?.unknown_remain>0?' · '+fmt(e.unknown_remain):''}</span>}</div>
}
export function Dashboard({accounts,connected,t,fmt,date,onAccount,onSettings,connectionState,demo,lastLoad,pluginPath}:{connectionState:string,demo:boolean,lastLoad:string,pluginPath:string,accounts:R[],connected:boolean,t:T,fmt:(n:any)=>string,date:(s:any)=>string,onAccount:(id:string)=>void,onSettings:()=>void}){
 const known=accounts.filter(a=>a.credits?.expiry?.known),soon=accounts.filter(a=>a.credits?.expiry?.within_7_days>0).sort((a,b)=>(expiryTimestamp(a.credits.expiry.next_at)??Infinity)-(expiryTimestamp(b.credits.expiry.next_at)??Infinity));
 return <div className="dashboard-workspace"><ConnectionInfo state={connectionState} demo={demo} lastLoad={lastLoad} pluginPath={pluginPath} t={t} date={date}/><div className="metrics">{[['total',connected?fmt(accounts.length):'—'],['knownCredits',accounts.some(a=>a.credits?.total_remain>=0)?fmt(accounts.reduce((n,a)=>n+Math.max(0,a.credits?.total_remain||0),0)):'—'],['expiring7',known.length?fmt(known.reduce((n,a)=>n+a.credits.expiry.within_7_days,0)):'—'],['expiryCoverage',connected?known.length+' / '+accounts.length:'—']].map(([label,value])=><section className="metric" key={label}><div>{t(label)}</div><strong>{value}</strong></section>)}</div><section className="panel expiry-panel"><div className="panel-heading"><h3>{t('expiringAccounts')}</h3><button className="button" onClick={onSettings}>{t('expiryStrategy')}</button></div><p className="muted">{t('expiryHint')}</p>{soon.length?soon.map(a=><button key={a.auth_index} className="expiry-account" onClick={()=>onAccount(a.auth_index)}><strong>{a.nickname||a.name}</strong><ExpiryNote credits={a.credits} t={t} fmt={fmt} date={date}/><small>{t('fetched')}: {date(a.credits.fetched_at)}</small></button>):<div className="empty">{t(known.length?'noExpiring':'noQuota')}</div>}</section><section className="panel attention-panel"><h3>{t('needsAttention')}</h3>{accounts.filter(a=>accountMatchesFilter(a,'attention')||a.data_error).map(a=><button className="expiry-account" key={a.auth_index} onClick={()=>onAccount(a.auth_index)}><strong>{a.nickname||a.name}</strong><span>{t(a.data_error?'dataReadFailed':a.disabled?'disabled':a.exhausted?'exhausted':'needsAttention')}</span></button>)}{!accounts.some(a=>accountMatchesFilter(a,'attention')||a.data_error)&&<p className="muted">{t(connected?'noAttention':'unknown')}</p>}</section></div>
}
export function PluginSettings({config,runtime,accounts,disabled,t,onChange,onRefresh,onMaintain}:{config:R|null,runtime:R|null,accounts:R[],disabled:boolean,t:T,onChange:(key:string,value:any)=>void,onRefresh:()=>void,onMaintain:()=>void}){
 const state=(key:string)=><small className={'setting-state '+settingState(config,runtime,key)}>{t('setting_'+settingState(config,runtime,key))}{settingState(config,runtime,key)==='differs'&&' · '+t('activeSettings')+': '+t(typeof runtime?.[key]==='boolean'?(runtime[key]?'enabled':'disabled'):'mode_'+runtime?.[key])}</small>;
 const group=(title:string,keys:string[])=><section className="settings-group"><h3>{t(title)}</h3>{keys.map(key=><div className="setting-row" key={key}><div><label htmlFor={'setting-'+key}>{t(key)}</label><p>{t(key+'Hint')}</p><div className="setting-meta"><small className="capability-scope">{t(['checkin_auto','travel_auto'].includes(key)?'domesticOnly':'bothRegions')} · {accounts.filter(a=>key==='travel_auto'?businessSupported(a,'travel')&&!a.disabled:key==='checkin_auto'?businessSupported(a,'checkin'):true).length} {t('account')}</small>{state(key)}</div></div><input id={'setting-'+key} type="checkbox" disabled={disabled||configuredSetting(config,key)===undefined} checked={configuredSetting(config,key)===true} onChange={e=>onChange(key,e.target.checked)}/></div>)}{title==='accountMaintenance'&&<div className="maintenance-action"><p className="muted">{t('maintenanceHint')}</p><button className="button" disabled={disabled} onClick={onMaintain}>{t('maintainAccounts')}</button></div>}</section>;
 const strategy=<section className="settings-group"><h3>{t('expiryStrategy')}</h3><div className="setting-row strategy-row"><div><label className="sr-only" htmlFor="expiry-mode">{t('expiryStrategy')}</label><p>{t(config?.scheduler_mode==='credits_expiry'?'expiryPolicyHint':'routingScopeHint')}</p>{state('scheduler_mode')}</div><select id="expiry-mode" value={configuredSetting(config,'scheduler_mode')||'host'} disabled={disabled||!config} onChange={e=>onChange('scheduler_mode',e.target.value)}>{['host','credits_expiry','credits','builtin','off'].map(x=><option key={x} value={x}>{t('mode_'+x)}</option>)}</select></div></section>;
 const travel=<section className="automation-run"><h3>{t('lastTravelRun')}</h3><p className="muted">{t('travelIndependentHint')}</p>{runtime?.business_hours&&<small>{runtime.business_hours.map((h:number)=>String(h).padStart(2,'0')+':00').join(' / ')} · {runtime.schedule_timezone||t('unknown')}</small>}{validTravelRun(runtime?.last_travel_run)?<div className="notice"><span>{t(runtime?.last_travel_run.status)} · {runtime?.last_travel_run.finished_at||runtime?.last_travel_run.started_at}</span><small>{t('processed')}: {runtime?.last_travel_run.attempted} · {t('success')}: {runtime?.last_travel_run.succeeded} · {t('failed')}: {runtime?.last_travel_run.failed} · {t('skipped')}: {runtime?.last_travel_run.skipped}</small>{runtime?.last_travel_run.error&&<small>{runtime?.last_travel_run.error}</small>}</div>:<p className="muted">{t(runtime?.last_travel_run===null?'noTravelRun':'travelRunUnknown')}</p>}</section>;
 return <section className="settings-workspace panel"><div className="settings-intro"><p className="muted">{t('pluginSettingsHint')}</p><button className="button" onClick={onRefresh} disabled={disabled}>{t('verifySettings')}</button></div><div className="settings-layout"><div className="settings-column">{group('businessAutomation',['checkin_auto','travel_auto'])}{strategy}</div><div className="settings-column">{group('accountMaintenance',['lifecycle_auto','token_keepalive'])}{travel}</div></div><div className="notice">{t('executionUnknown')}</div></section>
}
export function ModelMetadata({model:m,t,capabilitiesShown=false}:{model:R,t:T,capabilitiesShown?:boolean}){return <div className="model-metadata"><span className="model-efforts" title={t('reasoningTier')}>{m.efforts?.length?m.efforts.map((x:string)=><b key={x}>{x}</b>):'—'}{m.default_effort&&<small className="effort-default">{t('defaultTier')} {m.default_effort}</small>}{m.effective_effort&&<small className="effort-forced">{t('effectiveTier')} {m.effective_effort}</small>}</span><span className="model-flags"><span className={'model-rate '+(m.credits?'known':'')} title={t('multiplierHint')}>{m.credits||t('unverified')}</span>{!capabilitiesShown&&<span title={t('inputDeclarationHint')}>{m.supports_images===true?t('multimodal'):m.supports_images===false?t('textOnly'):t('unverified')}</span>}{m.is_default&&<span>{t('defaultModel')}</span>}{m.image_input_conflict&&<span>{t('imageConflictShort')}</span>}{m.only_reasoning&&<span>{t('reasoningOnly')}</span>}</span></div>}

export function ConnectionInfo({state,demo,lastLoad,pluginPath,t,date}:{state:string,demo:boolean,lastLoad:string,pluginPath:string,t:T,date:(s:any)=>string}){
 const label=state==='ok'?(demo?'demoConnected':'connected'):state==='checking'?'checkingConnection':state==='failed'?'connectionFailed':'disconnected';
 return <section className="connection-panel" aria-label={t('connectionInfo')} data-state={state}><div className="connection-heading"><h3>{t('connectionInfo')}</h3><span className={'connection-state '+(state==='ok'?'good':state==='failed'?'warn':'')} role="status"><i/>{t(label)}</span></div><details className="connection-technical"><summary>{t('details')}</summary><dl className="connection-facts"><div><dt>{t('sdk')}</dt><dd>CPA 8.0.15 · ABI 1 · Schema 6</dd></div><div><dt>{t('apiBoundary')}</dt><dd>v8 / v0</dd></div><div><dt>{t('lastAccountRead')}</dt><dd>{lastLoad?date(lastLoad):'—'}</dd></div></dl><details className="connection-path"><summary>{t('extensionPath')}</summary><code>{pluginPath}</code><p>{t('connectionScopeHint')}</p></details></details></section>
}
