import {NextExpiry} from './expiry-clock';
import React from 'react';
type R=Record<string,any>;type T=(key:string)=>string;
export const automationKeys=['checkin_auto','lifecycle_auto','token_keepalive','travel_auto'];
export const pluginDefaults:R={checkin_auto:true,lifecycle_auto:true,token_keepalive:false,travel_auto:false,scheduler_mode:'host'};
export function ExpiryNote({credits,t,fmt,date}:{credits?:R,t:T,fmt:(n:any)=>string,date:(s:any)=>string}){
 const e=credits?.expiry;return <div className="expiry-note"><NextExpiry credits={credits}/><strong>{t('expiring7')}: {e?.known?fmt(e.within_7_days):'—'}</strong>{e?.next_at&&<span>{t('nextExpiry')}: {date(e.next_at)} · {fmt(e.next_amount)}</span>}{(!e?.known||e?.unknown_remain>0)&&<span>{t('expiryUnknown')}{e?.unknown_remain>0?' · '+fmt(e.unknown_remain):''}</span>}</div>
}
export function Dashboard({accounts,connected,t,fmt,date,onAccount,onSettings,connectionState,demo,lastLoad,pluginPath}:{connectionState:string,demo:boolean,lastLoad:string,pluginPath:string,accounts:R[],connected:boolean,t:T,fmt:(n:any)=>string,date:(s:any)=>string,onAccount:(id:string)=>void,onSettings:()=>void}){
 const known=accounts.filter(a=>a.credits?.expiry?.known),soon=accounts.filter(a=>a.credits?.expiry?.within_7_days>0).sort((a,b)=>String(a.credits.expiry.next_at).localeCompare(String(b.credits.expiry.next_at)));
 return <div className="dashboard-workspace"><ConnectionInfo state={connectionState} demo={demo} lastLoad={lastLoad} pluginPath={pluginPath} t={t} date={date}/><div className="metrics">{[['total',connected?fmt(accounts.length):'—'],['knownCredits',accounts.some(a=>a.credits?.total_remain>=0)?fmt(accounts.reduce((n,a)=>n+Math.max(0,a.credits?.total_remain||0),0)):'—'],['expiring7',known.length?fmt(known.reduce((n,a)=>n+a.credits.expiry.within_7_days,0)):'—'],['expiryCoverage',connected?known.length+' / '+accounts.length:'—']].map(([label,value])=><section className="metric" key={label}><div>{t(label)}</div><strong>{value}</strong></section>)}</div><section className="panel expiry-panel"><div className="panel-heading"><h3>{t('expiringAccounts')}</h3><button className="button" onClick={onSettings}>{t('expiryStrategy')}</button></div><p className="muted">{t('expiryHint')}</p>{soon.length?soon.map(a=><button key={a.auth_index} className="expiry-account" onClick={()=>onAccount(a.auth_index)}><strong>{a.nickname||a.name}</strong><ExpiryNote credits={a.credits} t={t} fmt={fmt} date={date}/><small>{t('fetched')}: {date(a.credits.fetched_at)}</small></button>):<div className="empty">{t(known.length?'noExpiring':'noQuota')}</div>}</section></div>
}
export function PluginSettings({config,runtime,disabled,t,onChange,onRefresh}:{config:R|null,runtime:R|null,disabled:boolean,t:T,onChange:(key:string,value:any)=>void,onRefresh:()=>void}){
 return <section className="settings-workspace panel"><div className="panel-heading"><h3>{t('automation')}</h3><button className="button" onClick={onRefresh} disabled={disabled}>{t('verifySettings')}</button></div><p className="muted">{t('pluginSettingsHint')}</p>{automationKeys.map(key=><div className="setting-row" key={key}><div><label htmlFor={'setting-'+key}>{t(key)}</label><p>{t(key+'Hint')}</p><small>{t('activeSettings')}: {runtime? t(runtime[key]?'enabled':'disabled'):'—'}</small></div><input id={'setting-'+key} type="checkbox" disabled={disabled||!config} checked={!!(config?.[key]??pluginDefaults[key])} onChange={e=>onChange(key,e.target.checked)}/></div>)}<div className="setting-row"><div><label htmlFor="expiry-mode">{t('expiryStrategy')}</label><p>{t('expiryPolicyHint')}</p><small>{t('activeSettings')}: {runtime?t('mode_'+runtime.scheduler_mode):'—'}</small></div><select id="expiry-mode" value={config?.scheduler_mode||'host'} disabled={disabled||!config} onChange={e=>onChange('scheduler_mode',e.target.value)}>{['host','credits_expiry','credits','builtin','off'].map(x=><option key={x} value={x}>{t('mode_'+x)}</option>)}</select></div><div className="notice">{t('settingsConfirmHint')}</div></section>
}
export function ModelMetadata({model:m,t}:{model:R,t:T}){return <div className="model-metadata"><span className="model-efforts" title={t('reasoningTier')}>{m.efforts?.length?m.efforts.map((x:string)=><b key={x}>{x}</b>):'—'}{m.default_effort&&<small className="effort-default">{t('defaultTier')} {m.default_effort}</small>}{m.effective_effort&&<small className="effort-forced">{t('effectiveTier')} {m.effective_effort}</small>}</span><span className="model-flags"><span className={'model-rate '+(m.credits?'known':'')} title={t('multiplierHint')}>{m.credits||t('unverified')}</span><span title={t('inputDeclarationHint')}>{m.supports_images===true?t('multimodal'):m.supports_images===false?t('textOnly'):t('unverified')}</span>{m.is_default&&<span>{t('defaultModel')}</span>}{m.image_input_conflict&&<span>{t('imageConflictShort')}</span>}{m.only_reasoning&&<span>{t('reasoningOnly')}</span>}</span></div>}

export function ConnectionInfo({state,demo,lastLoad,pluginPath,t,date}:{state:string,demo:boolean,lastLoad:string,pluginPath:string,t:T,date:(s:any)=>string}){
 const label=state==='ok'?(demo?'demoConnected':'connected'):state==='checking'?'checkingConnection':state==='failed'?'connectionFailed':'disconnected';
 return <section className="connection-panel" aria-label={t('connectionInfo')} data-state={state}><div className="connection-heading"><h3>{t('connectionInfo')}</h3><span className={'connection-state '+(state==='ok'?'good':state==='failed'?'warn':'')} role="status"><i/>{t(label)}</span></div><dl className="connection-facts"><div><dt>{t('sdk')}</dt><dd>CPA 8.0.15 · ABI 1 · Schema 6</dd></div><div><dt>{t('apiBoundary')}</dt><dd>v8 / v0</dd></div><div><dt>{t('lastAccountRead')}</dt><dd>{lastLoad?date(lastLoad):'—'}</dd></div></dl><details className="connection-path"><summary>{t('extensionPath')}</summary><code>{pluginPath}</code><p>{t('connectionScopeHint')}</p></details></section>
}
